config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :pets
  resources :blogs
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :blog_categories
  has_many :categories, through: :blog_categories
  validates :title, presence: true, length: { minimum: 2, maximum: 100}
  validates :content, presence: true, length: { minimum: 8, maximum: 300}
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.paginate(page: params[:page], per_page: 3)
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(from_param)
    @blog.user = current_user
    if @blog.save
      flash[:notice] = "Blog title \"#{@blog.title}\" was saved sucessfully."
      redirect_to blogs_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @blog.update(from_param)
      flash[:notice] = "Blog title \"#{@blog.title}\" was saved sucessfully."
      redirect_to blogs_path
    else
      render 'edit'
    end
  end

  def destroy

    @blog.destroy
    redirect_to blogs_path
  end


  private
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def from_param
    params.require(:blog).permit(:title, :content, category_ids: [])
  end

  def require_same_user
    if current_user != @blog.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own blog!"
      redirect_to @blog
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="container">
  <% (@blogs.order created_at: :desc).each do |blog| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if blog.user %>
              by <%= link_to blog.user.user_name, user_path(blog.user) %>
            <% end %>
            <% if blog.categories.any? %>
              <div class="mt-2">
                <%= render blog.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <h3 class="card-title"><%= link_to blog.title, blog_path(blog), class: "text-warning" %></h3>
            <p class="card-text"><%= truncate blog.content, length: 100 %></p>
            <%= link_to "View", blog_path(blog), class: "btn btn-outline-success" %>
            <% if logged_in? && (blog.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_blog_path(blog), class: "btn btn-outline-info" %>
              <%= link_to "Delete", blog_path(blog), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words blog.created_at %> ago,
            edited <%= time_ago_in_words blog.updated_at %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/error', obj: @blog %>
      <%= form_with model: @blog, local: true, class: "shadow-sm rounded bg-secondary mb-3 p-3" do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light font-weight-bold" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of blog"%>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :content, class: "col-2 col-form-label text-light font-weight-bold" %>
          <div class="col-10">
            <%= f.text_area :content, rows: 10, class: "form-control shadow rounded", placeholder: "Content of blog"%>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, "Blog Category\n(can be empty)", class: "col-2 col-form-label text-light font-weight-bold" %>
          <div class="col-10" id="category_checkbox">
            <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
              <%= b.label do %>
                <%= b.check_box %>
                <span class="my_checkbox mr-1"><%= b.text %></span>
              <% end %>
            <% end %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      </div>

      <%= link_to '[Cancel and return to Blog List]', blogs_path, class: "text-dark mb-3" %>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div id="page-content-pet-index">
  <h1 class="text-center mt-4">Edit Blog</h1>


  <%= render 'form' %>

  <p>

  </p>
</div>

app/views/blogs/index.html.erb
<div id="page-content-pet-index">
  <h1 class="text-center mt-4">Cat Blogs for Kitty Life</h1>
  <div class="apple_pagination">
      <%= will_paginate @blogs, :container => false %>
  </div>
  <%= render 'blog' %>
  <div class="apple_pagination">
      <%= will_paginate @blogs, :container => false %>
  </div>
</div>

app/views/blogs/new.html.erb
<div id="page-content-pet-index">
  <h1 class="text-center mt-4">Write a new blog for kitty life</h1>
  <%= render 'form' %>
</div>

app/views/blogs/show.html.erb
<div id="page-content-pet-index">
  <h2 class="text-center mt-4"><%= @blog.title %></h2>

  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= ('by ' + @blog.user.user_name) if  @blog.user %>
            <%= link_to gravatar_for(@blog.user, size: 60), user_path(@blog.user) %>
            <% if @blog.categories.any? %>
              <div class="mt-2">
                <%= render @blog.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format @blog.content %></div>
            <% if logged_in? && (@blog.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_blog_path(@blog), class: "btn btn-outline-info" %>
              <%= link_to "Delete", blog_path(@blog), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words @blog.created_at %> ago,
            edited <%= time_ago_in_words @blog.updated_at %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>