config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :pets
  resources :blogs
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { minimum: 2, maximum: 100}
  validates :description, presence: true, length: { minimum: 8, maximum: 300}
  has_one_attached :photo
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @pets = Pet.paginate(page: params[:page], per_page: 3)
    @cat_emoji = cat_emoji_list
  end

  def show

  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(from_param)
    @pet.user = current_user
    if @pet.save
      flash[:notice] = "Pet \"#{@pet.name}\" was saved sucessfully."
      redirect_to pets_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    # @pet.photo.attach(params[:photo])
    if @pet.update(from_param)
      flash[:notice] = "Kitty Moment \"#{@pet.name}\" was updated sucessfully."
      redirect_to pets_path
    else
      render 'edit'
    end
  end

  def destroy

    @pet.destroy
    redirect_to pets_path
  end

  private

  def from_param
    params.require(:pet).permit(:name, :description, :photo)
  end

  def set_pet
    @pet = Pet.find(params[:id])
    @cat_emoji = cat_emoji_list
  end

  def require_same_user
    if current_user != @pet.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own kitty moment!"
      redirect_to @pet
    end
  end

end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<% if @pet.errors.any? %>
  <h2>Following error occured when saving new pets.</h2>
  <ul>
  <% @pet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_with model: @pet, local: true do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :Moment %><br/>
    <%= f.text_area :description, size: "60x12"%>
  </p>

  <p>
    <%= f.label :photo %><br/>
    <%= f.file_field :photo %>
  </p>

  <p>
    <%= f.submit class: "btn btn-primary" %>
  </p>

  <br>
<% end %>

app/views/pets/edit.html.erb
<div id="page-content-pet-index">
  <div class="container">
  <h1>Edit a Kitty Moment</h1>
  <%= render 'form' %>
  <p>
  <%= link_to 'Cancel and return home', pets_path %>
  </p>
  </div>
</div>

app/views/pets/index.html.erb
<div id="page-content-pet-index">
  <h1 class="text-center mt-4">The Kitty Moments</h1>
  <div class="apple_pagination">
      <%= will_paginate @pets, :container => false %>
  </div>
  <div class="container mt-4">
    <div class="card-deck">
      <% @pets.sort_by {|p| p.updated_at }.reverse.each do |p| %>
        <div class="card shadow-lg mb-4 rounded text-white bg-dark">
            <%= link_to pet_path(p) do %>
              <%= image_tag url_for(p.photo), alt: "image not added", class: "card-img-top rounded" if p.photo.attached? %>
            <% end %>
            <div class="card-body">
              <h4 class="card-title"><%= p.name + "\s" %>&#<%='x' + @cat_emoji.sample + ';' %></h4>
              <p class="card-text"><%= truncate p.description, length: 100 %></p>
              <div class="col text-center">
                <%= link_to "View", pet_path(p), class: "btn btn-warning" %>
                <% if logged_in? && (p.user == current_user || current_user.admin?) %>
                  <%= link_to "Edit", edit_pet_path(p), class: "btn btn-info" %>
                  <%= link_to "Delete", pet_path(p), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
                <% end %>
              </div>
            </div>
            <div class="card-footer">
              <small class="text-muted">Last updated at <%= p.updated_at.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y %I:%M%p") + " by "%><%= p.user ? link_to(p.user.user_name, p.user) : "admin" %></small>
            </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="apple_pagination">
      <%= will_paginate @pets, :container => false %>
  </div>
</div>

app/views/pets/new.html.erb
<div id="page-content-pet-index">
  <div class="container">
    <br>
    <h1>Create a new Kitty Moment</h1>
    <br>
    <%= render 'form' %>
    <p>
    <%= link_to 'Return to Kitty Moments', pets_path %>
    </p>
  </div>
</div>

app/views/pets/show.html.erb
<div id="page-content-pet-index">
  <div class="text-center mt-4">
    <h1 display-1><%= @pet.name %> &#<%='x' + @cat_emoji.sample + ';' %></h1>
    <h3 display-3><%= @pet.description%> </h3>
    <small>by <%= (link_to @pet.user.user_name, @pet.user, class: "text-info font-italic") if @pet.user %></small>
  </div>

  <div class="container">

    <div class="row justify-content-center mt-2 mb-2">
      <% if @pet.photo.attached? %>
        <%= image_tag url_for(@pet.photo), class: "cover rounded shadow p-2", alt: "Responsive image" %>
      <% end %>
    </div>
    <div class="col text-center mt-2 mb-2">
      <% if logged_in? && (@pet.user == current_user || current_user.admin?) %>
        <%= link_to "Edit", edit_pet_path(@pet), class: "btn btn-info mr-5" %>
        <%= link_to "Delete", pet_path(@pet), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
      <% end %>
    </div>
    <div class="row justify-content-center">
      <%= link_to 'Return to Kitty Moments', pets_path, class: "text-secondary mb-2 mt-2"%>
    </div>

  </div>
</div>