config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :pets
  resources :blogs
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/models/category.rb
class Category < ApplicationRecord
  before_save do
    self.name = name.upcase
  end
  has_many :blog_categories
  has_many :blogs, through: :blog_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end

  def show
    @blogs = @category.blogs.paginate(page: params[:page], per_page: 4)
  end

  def create
    @category = Category.new(from_param)
    if @category.save
      flash[:notice] = "sucessfully saved."
      redirect_to @category
    else
      render 'new'
    end
  end

  def update
    if @category.update(from_param)
      redirect_to @category, notice: "Category \"#{@category.name}\" sucessfully updated."
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def from_param
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category, class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/error', obj: @category %>
      <%= form_with model: @category, local: true, class: "shadow-sm rounded bg-secondary mb-3 p-3" do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category Name", class: "col-2 col-form-label text-light font-weight-bold" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "name of category"%>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      </div>
    <% end %>
    <%= link_to '[Cancel and return to Category List]', categories_path, class: "text-dark mb-3" %>
  </div>
</div>

app/views/categories/edit.html.erb
<div id="page-content-pet-index">
  <h1 class="text-center mt-4">Edit user info</h1>
  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div id="page-content-pet-index">
  <h1 class="text-center mt-4">Categories</h1>

  <div class="apple_pagination">
      <%= will_paginate @categories, :container => false %>
  </div>

  <div class="container">
    <% (@categories.order created_at: :desc).each do |category| %>
      <div class="row justify-content-md-center">
        <div class="col-4 mt-3">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-body">
              <h3 class="card-title"><%= link_to category.name.upcase, category, class: "text-warning" %></h3>
              <p class="card-text"><%= pluralize category.blogs.count, "Blog" %></p>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words category.created_at %> ago,
              edited <%= time_ago_in_words category.updated_at %> ago</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="apple_pagination">
      <%= will_paginate @categories, :container => false %>
  </div>

</div>

app/views/categories/new.html.erb
<div id="page-content-pet-index">
  <h1 class="text-center mt-4">New Category</h1>
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<div id="page-content-pet-index">
  <h1 class="text-center mt-4">Category : <%= @category.name.upcase %></h1>
  <div class="text-center mt-4">
    <% if logged_in? && current_user.admin? %>
      <%= link_to "Edit category", edit_category_path(@category), class: "btn btn-info" %>
    <% end %>
  </div>
  <h3 class="text-center mt-5">Blogs</h3>
  <div class="apple_pagination">
      <%= will_paginate @blogs, :container => false %>
  </div>
  <%= render 'blogs/blog' %>
  <div class="apple_pagination">
      <%= will_paginate @blogs, :container => false %>
  </div>
</div>