config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :pets
  resources :blogs
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Dale Foskey", "https://johnnydalefoskey.org", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show text-center mb-0" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-light">
   <%= link_to 'Cat Log', root_path, class: "navbar-brand", id: "logo"%>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>

   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav mr-auto">
       <li class="nav-item">
         <%= link_to "Cat Loggers", users_path, class: "nav-link" %>
       </li>
       <li class="nav-item active">
         <%= link_to "Blogs", blogs_path, class: "nav-link" %>
       </li>
       <li class="nav-item">
         <%= link_to "Kitties", pets_path, class: "nav-link" %>
       </li>
       <li class="nav-item">
         <%= link_to "Categories", categories_path, class: "nav-link" %>
       </li>
       <% if logged_in? %>
         <li class="nav-item">
           <%= link_to (current_user.admin? ? "[Admin]" : "") + current_user.user_name + "\'s Profile", current_user, class: "nav-link" %>
         </li>
         <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Actions
           </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdown">
             <%= link_to "Write a new blog", new_blog_path, class: "dropdown-item"  %>
             <%= link_to "Add a new Kitty Moment", new_pet_path, class: "dropdown-item"  %>
             <% if current_user.admin? %>
              <%= link_to "Create new Category", new_category_path, class: "dropdown-item" %>
             <% end %>
             <div class="dropdown-divider"></div>
             <%= link_to "Edit #{current_user.user_name}'s profile", edit_user_path(current_user), class: "dropdown-item text-info" %>
             <%= link_to "Delete #{current_user.user_name}'s profile", current_user, method: :delete, data: { confirm: "Are you sure?" }, class: "dropdown-item text-danger" %>
             <div class="dropdown-divider"></div>
             <%= link_to "Log Out", login_path, method: :delete, class: "dropdown-item text-warning" %>
           </div>
         </li>
       <% else %>
         <li class="nav-item">
           <%= link_to "Log In", login_path, class: "nav-link" %>
         </li>
         <li class="nav-item">
           <%= link_to "Sign Up", signup_path, class: "nav-link" %>
         </li>
       <% end %>
     </ul>
     <form class="form-inline my-2 my-lg-0">
       <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
       <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
     </form>
   </div>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Cat Log</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>

</html>